#!/bin/bash

thisdir=$(realpath $(dirname ${0}))

if [[ -f ${thisdir}/${2} ]]; then 
    echo ${2} already exists
else
    echo _execute ${1} ${2} '${@}' > ${thisdir}/${2}
    chmod +x ${thisdir}/${2}
fi